# Generated by Django 4.0.4 on 2022-07-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
