# Generated by Django 4.0.6 on 2022-07-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_slug',
            field=models.SlugField(blank=True),
        ),
    ]
